allowBuilds:
  sharp: set this to true or false
minimumReleaseAgeExclude:
  - '@aboutcircles/miniapp-sdk@0.1.44'
  - '@aboutcircles/miniapp-sdk@0.1.46'
onlyBuiltDependencies:
  - sharp
verifyDepsBeforeRun: false
